chillipharm-ruby-tech-test/config/routes.rb
Rails.application.routes.draw do
  root to: "libraries#index"

  resources :users
  resources :libraries do
    member do
      get :info
    end

    resources :assets do
      resources :comments

      collection do
        get :delete
        delete :delete
      end
    end
  end
end

chillipharm-ruby-tech-test/app/views/shared/_activity_list.html.erb
<% @activity.each do |activity| %>
  <div class="media row-highlight">
    <div class="media-left">
      <%= avatar("img-responsive avatar small") %>
    </div>
    <div class="media-body">
      <p><%= render partial: "activity/#{activity.action}.html.erb", locals: { activity: activity } %></p>
      <p><i><%= date_format(activity.created_at) %></i></p>
    </div>
  </div>
<% end %>

chillipharm-ruby-tech-test/app/views/shared/_analytics.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-7607754-11', 'auto');
    ga('send', 'pageview');
  </script>
<% end %>

chillipharm-ruby-tech-test/app/views/shared/_asset_layout.html.erb
<div id="header">
  <div class="container-fluid">
    <div class="row sub-header dark clearfix">
      <div class="col-xs-12">
        <ol class="breadcrumb">
          <li><%= link_to current_library.name, library_path(current_library) %></li>
          <% if defined? @asset %>
            <li><%= @asset.title %></li>
          <% end %>
        </ol>
      </div>
    </div>
    <div class="row sub-header light clearfix">
      <div class="col-xs-12">
        <ul class="action-bar" id="action-bar-asset">
          <li class="action-bar-action">
            <div class="dropdown add-to">
              <a class="action dropdown-toggle" id="add-to" data-toggle="dropdown" aria-expanded="true">Add to&hellip;
                <span class="caret"></span>
              </a>
            </div>
            <span class="action-divider"></span>
          </li>
        </ul>
      </div>
    </div>
    <div class="row sub-header light show-collections-mobile text-align-r">
      <div class="col-xs-12">
      </div>
    </div>
  </div>
</div>
<div id="content-section-wrap">
  <div id="asset" class="content-section" data-id="<%= @asset.id %>">
    <div class="container-fluid">
      <div id="asset-wrap">
        <% if @asset.video? %>
          <% if has_transform(@asset) %>          
            <%= render 'account/assets/shared/video_player', locals: { asset: @asset } %>
          <% else %>
            <div id="video-pending">
              <h2>Media Transcoding...</h2>
              <p>Web proxy not yet available for playback.</p>
            </div>
            <%= asset_thumbnail(@asset, "640x480", "img-responsive") %>
          <% end %>
        <% elsif @asset.image? %>
          <%= asset_thumbnail(@asset, "640x480", "img-responsive") %>
        <% else %>
          <%= image_tag("asset-icons/large/unknown.gif", class: "unknown img-responsive") %>
        <% end %>
      </div>
      <div class="row sub-header mid clearfix">
        <div class="col-xs-12">
          <%= render 'assets/shared/navigation' %>
        </div>
      </div>
      <div class="row">
        <%= yield :asset_tab_content %>
      </div>
    </div>
  </div>
</div>

chillipharm-ruby-tech-test/app/views/shared/_display_options.html.erb
<div id="library-display-options" class="display-options no-pad">
    <ul>
      <li>
        <%= link_to request.url, request.params.merge(display_assets: 'display_assets_as_list') do %>
          <i class="fa fa-align-justify"></i>
          <span>List</span>
        <% end %>
      </li>
      <li>
        <a class="grid <%= (params['display_assets'].eql?('display_assets_as_grid') || params['display_assets'].nil?) ? 'active' : '' %>" href="?display_assets=display_assets_as_grid">
          <i class="fa fa-th-large"></i>
          <span>Grid</span>
        </a>        
      </li>
    </ul>
</div>

chillipharm-ruby-tech-test/app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div>
  <div class="pop-message notice" style="">
    <% if type.eql?("error") %>
      <i class="fa fa-exclamation-triangle animated"></i>
    <% else %>
      <i class="fa fa-check animated"></i>
    <% end %>
    <% formatted_message = "" %>
    <% message_array = message.split("<br>") %>
    <% message_array.each do |sentence| %>
      <%= sentence %><br><br>
    <% end %>
    <a href="javascript:parent.$.fancybox.close();" class="cancel-link center">Close</a>
  </div>
</div>
<% end %>

chillipharm-ruby-tech-test/app/views/shared/_grid_asset.html.erb
<div class="asset" id="asset-<%= asset.id %>" data-id="<%= asset.id %>">
  <div class="asset-content item">
    <%= asset_thumbnail(asset, "150x150") %>
    <div class="asset-badges file-type-badge <%= asset_file_type_icon(asset) %>"></div>
    <%= link_to library_asset_path(current_library, asset) do %>
      <div class="asset-badges open-asset-badge-grid"></div>
    <% end %>
    <div class="asset-info clearfix">
      <%= link_to asset.title.to_s, "#", class: "asset-tool", "data-toggle" => "tooltip", title: asset.title %>
    </div>
  </div>
  <% if asset.video? %>
    <div class="hidden-content">
    </div>
  <% end %>
</div>

chillipharm-ruby-tech-test/app/views/shared/_list_asset.html.erb
<tr class="tr-asset-content" id="asset-<%= asset.id %>" data-id="<%= asset.id %>">
  <td data-th="Select Asset">
    <div class="checkbox">
      <label>
        <input type="checkbox" class="check-move uncheck-checkbox">
      </label>
    </div>
  </td>
  <td>
    <a href="<%= library_asset_path(current_library, asset) %>" data-toggle="tooltip" data-placement="bottom" title="" class="list-thumb">
      <div class="<%= list_view_video_status(asset) %>"></div>
      <%= asset_thumbnail(asset, "150x150", "img-responsive") %>
    </a>
  </td>
  <!-- Important - Use the 'table-element-ellipsis' class to ensure the tooltip can find the center of this element -->
  <td data-th="Title: "><a href="<%= library_asset_path(current_library, asset) %>" class="table-element-ellipsis" data-toggle="tooltip" data-placement="top" title="<%= asset.title if asset.title %>"><%= asset.title %></a></td>

  <td data-th="Date Added: "><span><%= date_format(asset.created_at) %></span></td>
  <td class="hidden-th-td">
    <% empty_class = asset.comments.any? ? "" : "no-comments" %>
    <a href="<%= library_asset_comments_path(current_library, asset) %>" class="table-element-ellipsis <%= empty_class %>">
      <i class="fa fa-comment"></i><%= asset.comments_count %>
    </a>
  </td>
  <td class="hidden-th-td">
    <a href="<%= library_asset_path(current_library, asset) %>">
      <div class="open-asset-badge-list"></div>
    </a>
  </td>
</tr>

chillipharm-ruby-tech-test/app/views/shared/_user_pill.html.erb
<div class="row">
  <ul class="pill-list">
  </ul>
</div>
<div class="row">
  <ul class="pill-list">
  </ul>
</div>
<%= link_to avatar("", "40x40") %>