chillipharm-ruby-tech-test/config/routes.rb
Rails.application.routes.draw do
  root to: "libraries#index"

  resources :users
  resources :libraries do
    member do
      get :info
    end

    resources :assets do
      resources :comments

      collection do
        get :delete
        delete :delete
      end
    end
  end
end

chillipharm-ruby-tech-test/app/models/library.rb
class Library < ApplicationRecord
  acts_as_paranoid

  has_many :assets
  belongs_to :creator, class_name: "User"

  validates :name, presence: true

  def self.alphabetical
    order("name ASC")
  end
end

chillipharm-ruby-tech-test/app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def show
    @assets = Asset.search(params[:search], current_library.id)
    # library_id: current_library.id
  end

  def index
    @libraries = Library.all
    render layout: "library_dashboard"
  end

  def activity
    @activity = current_library.activities
    @activity = current_library.activities.order(created_at: :desc)

    render partial: "shared/activity_list", layout: false if request.xhr?
  end

  def info
    render layout: false if request.xhr?
  end
end

chillipharm-ruby-tech-test/app/helpers/account/libraries_helper.rb
module Account::LibrariesHelper
  def current_filter_label(filter)
    case filter
    when "video"
      "Video Only"
    when "audio"
      "Audio Only"
    when "image"
      "Image Only"
    else
      "All File Types"
    end
  end

  def current_sort_label(sort)
    case sort
    when "created_at_asc"
      "Oldest"
    when "created_at_desc"
      "Most Recent"
    when "title_asc"
      "Title A-Z"
    when "title_desc"
      "Title Z-A"
    else
      "Most Recent"
    end
  end

  def filter_link(filter, sort, search, section, library, object = nil)
    args = {}

    args[:filter] = filter

    if sort.present?
      args[:sort] = sort
    end

    if search.present?
      args[:search] = search
    end

    section_link(library, section, args, object)
  end

  def sort_link(sort, filter, search, section, library, object = nil)
    args = {}
    args[:sort] = sort

    if filter.present?
      args[:filter] = filter
    end

    if search.present?
      args[:search] = search
    end

    section_link(library, section, args, object)
  end

  def section_link(library, section, args, object = nil)
    case section
    when "library"
      library_path(library, args)
    when "collection"
      library_collection_path(library, object, args)
    else
      library_path(library, args)
    end
  end
end

chillipharm-ruby-tech-test/app/views/libraries/_favourites.html.erb
<div id="favourites">
  <% if current_user.favourite_libraries_for_account(current_account).empty? %>
    <div id="fav-placeholder">
      <i class="fa fa-th"></i>
      <h3 class="marg-bottom-0">Favourited libraries appear here for easy access</h3>
    </div>
  <% else %>
    <div class="row">
      <% current_user.favourite_libraries_for_account(current_account).each do |library| %>
        <div class="col-md-4" id="favourite-library-<%= library.id %>">
          <div class="favourites-wrap">
            <%= link_to library.name, library_path(library), class: 'large-library-link' %>
            <% library.recent_activities.each do |activity| %>
              <div class="media favourite">
                <div class="media-left">
                  <%= avatar("img-responsive avatar small") %>
                </div>
                <div class="media-body">
                  <p><%= render partial: "activity/#{activity.action}.html.erb", locals: { activity: activity } %></p>
                  <p><i><%= date_format(activity.created_at) %></i></p>
                </div>
              </div>
            <% end %>
            <% if library.recent_activities.empty? %>
              <p class="no-activity"><i>No Activity...</i></p>
            <% end %>
            <div class="fav-bottom-panel clearfix">
              <ul>
                <li>
                  <%= library.assets.count %>
                </li>
                <li class="white">
                  <i class="fa fa-star favourited" data-behaviour="library_favourite" data-library-id="<%= library.id %>"></i>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

chillipharm-ruby-tech-test/app/views/libraries/_grid_view.html.erb
<div id="content-section-wrap">
  <div id="assets" class="content-section grid">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <%= render partial: 'shared/grid_asset', collection: @assets, as: :asset %>
        </div>
      </div>
    </div>
  </div>
</div>

chillipharm-ruby-tech-test/app/views/libraries/_list_view.html.erb
<div id="content-section-wrap">
  <div id="assets" class="content-section list">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 no-pad">
          <table class="list-table">
            <tr class="sub-header dark hidden-tr">
              <th></th>
              <th></th>
              <th>
                <% if params[:sort] && params[:sort].eql?("title_desc") %>
                  <%= link_to content_tag(:i, "", class: "fa fa-sort-alpha-desc"), sort_link(:title_asc, params[:filter], params[:search], "library", current_library) %>
                <% elsif params[:sort] && params[:sort].eql?("title_asc") %>
                  <%= link_to content_tag(:i, "", class: "fa fa-sort-alpha-asc"), sort_link(:title_desc, params[:filter], params[:search], "library", current_library) %>
                <% else %>
                <%= link_to content_tag(:i, "", class: "fa fa-sort"), sort_link(:title_asc, params[:filter], params[:search], "library", current_library) %>
                <% end %> Title
              </th>
              <th>
                <% if params[:sort] && params[:sort].eql?("created_at_desc") %>
                  <%= link_to content_tag(:i, "", class: "fa fa-sort-down"), sort_link(:created_at_asc, params[:filter], params[:search], "library", current_library) %>
                <% elsif params[:sort] && params[:sort].eql?("created_at_asc") %>
                  <%= link_to content_tag(:i, "", class: "fa fa-sort-up"), sort_link(:created_at_desc, params[:filter], params[:search], "library", current_library) %>
                <% else %>
                <%= link_to content_tag(:i, "", class: "fa fa-sort"), sort_link(:created_at_asc, params[:filter], params[:search], "library", current_library) %>
                <% end %>
                Upload Date
              </th>
              <th></th>
              <th></th>
            </tr>
            <%= render partial: 'shared/list_asset', collection: @assets, as: :asset %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

chillipharm-ruby-tech-test/app/views/libraries/_recent_libraries.html.erb
<div id="recent-libraries">
  <% if @recent_libraries.empty? %>
    <div id="recent-placeholder">
      <i class="fa fa-th"></i>
      <h3 class="marg-bottom-0">There are no recently active libraries</h3>
    </div>
  <% else %>
    <div class="row">
      <% @recent_libraries.each do |library| %>
        <div class="col-md-4" id="recent-library-<%= library.id %>">
          <div class="favourites-wrap">
            <%= link_to library.name, library_path(library), class: 'large-library-link' %>
            <% library.recent_activities.each do |activity| %>
              <div class="media recent activity">
                <div class="media-left">
                  <%= avatar("img-responsive avatar small") %>
                </div>
                <div class="media-body">
                  <p><%= render partial: "activity/#{activity.action}.html.erb", locals: { activity: activity } %></p>
                  <p><i><%= date_format(activity.created_at) %></i></p>
                </div>
              </div>
            <% end %>
            <% if library.recent_activities.empty? %>
              <p class="no-activity"><i>No Activity...</i></p>
            <% end %>
            <div class="fav-bottom-panel clearfix">
              <ul>
                <li>
                  <%= library.assets.count %>
                </li>
                <li class="white">
                  <i class="fa fa-star <%=  "favourited" if current_user.favourite_libraries_for_account(current_account).include?(library) %>" data-behaviour="library_favourite" data-library-id="<%= library.id %>"></i>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

chillipharm-ruby-tech-test/app/views/libraries/activity.html.erb
<div id="header">
  <div class="container-fluid">
    <div class="row sub-header dark clearfix">
      <div class="col-xs-12">
        <ol class="breadcrumb">
          <li><%= link_to current_library.name, library_path(current_library) %></li>
          <li>Activity</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<div id="content-section-wrap">
  <div class="content-section no-pad">
    <div class="container-fluid">
      <% if @activity.any? %>
        <div class="row">
          <div class="col-xs-12 no-pad">
            <%= render 'shared/activity_list' %>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="well placeholder">
              <h3>No Library Activity!</h3>
              <p>Nothing has happened yet...</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

chillipharm-ruby-tech-test/app/views/libraries/index.html.erb
<% if @libraries.any? %>
<div class="row marg-top-20" id="libraries-header">
  <div class="col-md-6">
    <form role="form">
      <div class="form-group">
        <label>Filter by name</label>
        <input type="text" class="form-control" id="library-search" name="library-search" placeholder="Filter by name">
      </div>
    </form>
    <span id="a-z-options">
      Sort Alphabetically:
      <% if params[:sort] && params[:sort].eql?("alphabetical") %>
        <%= link_to("Off", libraries_path(display_libraries: "display_favourite_libraries"), class: view_type_active('display_favourite_libraries'), "data-toggle" => "tooltip", "title"=> "Sort by the order defined by Administrators") %>
      <% else %>
        <%= link_to("On", libraries_path(display_libraries: "display_favourite_libraries", sort: "alphabetical"), class: view_type_active('display_favourite_libraries')) %>
      <% end %>
    </span>
  </div>
</div>
<ul id="libraries-list">
  <% @libraries.each do |library| %>
    <li class="library" id="library-<%= library.id %>">
      <i class="fa fa-star <%= library_favourited_class(current_user, library) %>" data-behaviour="library_favourite" data-library-id="<%= library.id %>"></i>
      <%= link_to library.name, library_path(library), class: 'dashboard-library-link large-library-link' %>
    </li>
  <% end %>
</ul>
<p class="no-libraries-found" style="display:none">No Libraries found. Please check your spelling and try again!</p>
<% else %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well placeholder marg-top-20 marg-bottom-0">
          <p>The Application is up an running!</p>
          <p>Now just run <b><i>rake db:seed</i></b> to get some sample data</p>
        </div>
      </div>
    </div>
  </div>
<% end %>

chillipharm-ruby-tech-test/app/views/libraries/info.html.erb
<div class="fancybox-titlebar">
  Library Info
</div>
<form>
  <div class="fancybox-content">
    <dl class="flex-width">
      <dt>Total Assets:</dt>
      <dd><%= current_library.assets.count %></dd>
      <dt>Total Asset Size:</dt>
      <dd><%= number_to_human_size current_library.assets.sum(:filesize) %></dd>
      <dt>Created at:</dt>
      <dd><%= date_format(current_library.created_at) %></dd>
    </dl>
  </div>
  <div class="fancybox-content clearfix">
    <a href="javascript:parent.$.fancybox.close();" class="cancel-link left">Cancel</a>
  </div>
</form>

chillipharm-ruby-tech-test/app/views/libraries/show.html.erb
<div id="header">
  <div class="container-fluid">
    <div class="row sub-header dark clearfix">
      <div class="col-xs-12 col-sm-8">
        <% if params[:search].present? %>
          Search Results for: <%= params[:search] %>
        <% elsif params[:search_fields].present? %>
          Search Results for: <%= params[:search_fields].to_unsafe_h.map { |key, val| val.last }.join(", ") %>
        <% else %>
          All Content
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= render 'shared/display_options' %>
      </div>
    </div>
    <div class="row sub-header product-branding product-branding-asset-listing clearfix">
      <div class="col-xs-12">
        <%= link_to " Library Info", info_library_path(current_library), class: "fancybox action", "data-fancybox-type" => "ajax", style: "float: right; text-decoration:underline;" %>
      </div>
    </div>
    <div class="row sub-header light">
      <div class="col-md-12 col-lg-4 select-all">
        <div class="checkbox">
          <label>
            <input type="checkbox" class="uncheck-checkbox"> Select All
          </label>
        </div>
        <p class="select-assets marg-bottom-0"><%= pluralize @assets.length, "Asset" %></p>
      </div>
      <div class="col-md-12 col-lg-8">
        <ul class="action-bar">
          <li class="action-bar-action"><%= link_to "Download", "#", class: "action disabled-action disabled-action-true" %>
            <span class="action-divider"></span>
          </li>
          <li class="action-bar-action"><%= link_to "Delete", delete_library_assets_path(current_library), class: "fancybox action delete disabled-action disabled-action-true", "data-fancybox-type" => "ajax" %>
            <span class="action-divider"></span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="content-section clearfix">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="dropdown filter-actions">
          <span>Filter By: </span>
          <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
            <%= current_filter_label(params[:filter]) %>
          </a>
          <ul class="dropdown-menu change-value dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu">
            <li role="presentation"><%= link_to "All File Types", filter_link("all", params[:sort], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "filter", "data-filter-value" => "all" %></li>
            <li role="presentation"><%= link_to "Video Only", filter_link("video", params[:sort], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "filter", "data-filter-value" => "video" %></li>
            <li role="presentation"><%= link_to "Audio Only", filter_link("audio", params[:sort], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "filter", "data-filter-value" => "audio" %></li>
            <li role="presentation"><%= link_to "Images Only", filter_link("image", params[:sort], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "filter", "data-filter-value" => "image" %></li>
          </ul>
        </div>
        <div class="dropdown filter-actions">
          <span>Sort By: </span>
          <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
            <%= current_sort_label(params[:sort]) %>
          </a>
          <ul class="dropdown-menu change-value dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu">
            <li role="presentation"><%= link_to "Most Recent", sort_link(:created_at_desc, params[:filter], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "sort", "data-filter-value" => "created_at_desc" %></li>
            <li role="presentation"><%= link_to "Oldest", sort_link(:created_at_asc, params[:filter], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "sort", "data-filter-value" => "created_at_asc" %></li>
            <li role="presentation"><%= link_to "Title A-Z", sort_link(:title_asc, params[:filter], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "sort", "data-filter-value" => "title_asc" %></li>
            <li role="presentation"><%= link_to "Title Z-A", sort_link(:title_desc, params[:filter], params[:search], "library", current_library), role: "menuitem", "data-filter-key" => "sort", "data-filter-value" => "title_desc" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @assets.any? %>
  <% if params['display_assets'].eql?('display_assets_as_list') %>
    <%= render 'list_view' %>
  <% else %>
    <%= render 'grid_view' %>
  <% end %>
<% elsif params[:search].present? || params[:search_fields].present? || params[:filter].present? %>
  <div id="assets" class="content-section">
    <div class="row no-marg">
      <div class="col-md-6 col-md-offset-3">
        <div class="well placeholder">
          <h4>No Search Results</h4>
          <p>Your search returned no results, please try an alternative search.</p>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div id="content-section-wrap">
    <div id="assets" class="content-section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="well placeholder">
              <h3>Welcome to Your New Library!</h3>
              <p>To get started, upload content using the bar above, then organize it into collections using the menu on the left.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>